version: 2

models:
  - name: stg_matches
    description: "Staged match metadata with cleaned types and normalized seasons"
    columns:
      - name: match_id
        description: "Unique Cricsheet match identifier"
        tests:
          - unique
          - not_null
      - name: season
        tests:
          - not_null
      - name: match_date
        tests:
          - not_null

  - name: stg_deliveries
    description: "Staged ball-by-ball data with computed flags"
    columns:
      - name: match_id
        tests:
          - not_null
      - name: batter
        tests:
          - not_null
      - name: bowler
        tests:
          - not_null

  - name: stg_people
    description: "Staged player/official registry"
    columns:
      - name: player_id
        description: "8-char hex identifier"
        tests:
          - unique
          - not_null
      - name: player_name
        tests:
          - not_null
