name: cricket_analytics
version: "0.1.0"
config-version: 2

profile: cricket_analytics

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  cricket_analytics:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table

seeds:
  cricket_analytics:
    +schema: seeds
